# Configuração de aplicação usando TOML
title = "Configuração do Sistema"
version = "1.0.0"
debug = false

# Configuração de database
[database]
host = "localhost"
port = 5432
user = "admin"
password = "secret123"
database = "myapp"
pool_size = 10
timeout = 30

[database.ssl]
enabled = true
cert_file = "/path/to/cert.pem"
key_file = "/path/to/key.pem"

# Configuração de Redis
[cache]
host = "localhost"
port = 6379
db = 0
password = ""
ttl = 3600

# Configuração da API
[api]
host = "0.0.0.0"
port = 8000
workers = 4
reload = false
log_level = "info"

[api.cors]
enabled = true
origins = ["http://localhost:3000", "https://example.com"]
methods = ["GET", "POST", "PUT", "DELETE"]
headers = ["Content-Type", "Authorization"]

# Configuração de logging
[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file = "/var/log/app/app.log"
max_bytes = 10485760  # 10MB
backup_count = 5

[logging.handlers]
console = true
file = true
syslog = false

# Features flags
[features]
enable_api_v2 = false
enable_caching = true
enable_metrics = true
enable_tracing = false

# Array of tables - múltiplos servidores
[[servers]]
name = "prod-01"
host = "prod-01.example.com"
port = 8080
region = "us-east-1"
enabled = true

[[servers]]
name = "prod-02"
host = "prod-02.example.com"
port = 8080
region = "us-west-1"
enabled = true

[[servers]]
name = "staging"
host = "staging.example.com"
port = 8000
region = "us-east-1"
enabled = false
