pipelines:
  - name: example
    steps:
      - parallel:
        - name: first
          commands:
            - uv run poe test
        - name: second
          commands:
            - uv run poe lint
