# coding: utf-8

# flake8: noqa
"""
    FakeStoreAPI

    A free fake API for testing and prototyping e-commerce applications.

    The version of the OpenAPI document: v2.1.11
    Contact: support@fakestoreapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.cart import Cart
from openapi_client.models.login import Login
from openapi_client.models.login_response import LoginResponse
from openapi_client.models.product import Product
from openapi_client.models.user import User

