# coding: utf-8

"""
    FakeStoreAPI

    A free fake API for testing and prototyping e-commerce applications.

    The version of the OpenAPI document: v2.1.11
    Contact: support@fakestoreapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.products_api import ProductsApi


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductsApi()

    def tearDown(self) -> None:
        pass

    def test_add_product(self) -> None:
        """Test case for add_product

        Add a new product
        """
        pass

    def test_delete_product(self) -> None:
        """Test case for delete_product

        Delete a product
        """
        pass

    def test_get_all_products(self) -> None:
        """Test case for get_all_products

        Get all products
        """
        pass

    def test_get_product_by_id(self) -> None:
        """Test case for get_product_by_id

        Get a single product
        """
        pass

    def test_update_product(self) -> None:
        """Test case for update_product

        Update a product
        """
        pass


if __name__ == '__main__':
    unittest.main()
