# coding: utf-8

"""
    FakeStoreAPI

    A free fake API for testing and prototyping e-commerce applications.

    The version of the OpenAPI document: v2.1.11
    Contact: support@fakestoreapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.carts_api import CartsApi


class TestCartsApi(unittest.TestCase):
    """CartsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CartsApi()

    def tearDown(self) -> None:
        pass

    def test_add_cart(self) -> None:
        """Test case for add_cart

        Add a new cart
        """
        pass

    def test_delete_cart(self) -> None:
        """Test case for delete_cart

        Delete a cart
        """
        pass

    def test_get_all_carts(self) -> None:
        """Test case for get_all_carts

        Get all carts
        """
        pass

    def test_get_cart_by_id(self) -> None:
        """Test case for get_cart_by_id

        Get a single cart
        """
        pass

    def test_update_cart(self) -> None:
        """Test case for update_cart

        Update a cart
        """
        pass


if __name__ == '__main__':
    unittest.main()
