# coding: utf-8

"""
    FakeStoreAPI

    A free fake API for testing and prototyping e-commerce applications.

    The version of the OpenAPI document: v2.1.11
    Contact: support@fakestoreapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cart import Cart

class TestCart(unittest.TestCase):
    """Cart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Cart:
        """Test Cart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Cart`
        """
        model = Cart()
        if include_optional:
            return Cart(
                id = 56,
                user_id = 56,
                products = [
                    openapi_client.models.product.Product(
                        id = 56, 
                        title = '', 
                        price = 1.337, 
                        description = '', 
                        category = '', 
                        image = '', )
                    ]
            )
        else:
            return Cart(
        )
        """

    def testCart(self):
        """Test Cart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
