# coding: utf-8

"""
    FakeStoreAPI

    A free fake API for testing and prototyping e-commerce applications.

    The version of the OpenAPI document: v2.1.11
    Contact: support@fakestoreapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_add_user(self) -> None:
        """Test case for add_user

        Add a new user
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete a user
        """
        pass

    def test_get_all_users(self) -> None:
        """Test case for get_all_users

        Get all users
        """
        pass

    def test_get_user_by_id(self) -> None:
        """Test case for get_user_by_id

        Get a single user
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        Update a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
