# generated by datamodel-codegen:
#   filename:  https://fakestoreapi.com/docs-data
#   timestamp: 2025-11-01T15:34:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import AnyUrl, BaseModel


class Product(BaseModel):
    id: Optional[int] = None
    title: Optional[str] = None
    price: Optional[float] = None
    description: Optional[str] = None
    category: Optional[str] = None
    image: Optional[AnyUrl] = None


class Cart(BaseModel):
    id: Optional[int] = None
    userId: Optional[int] = None
    products: Optional[List[Product]] = None


class User(BaseModel):
    id: Optional[int] = None
    username: Optional[str] = None
    email: Optional[str] = None
    password: Optional[str] = None


class Login(BaseModel):
    username: Optional[str] = None
    password: Optional[str] = None


class LoginResponse(BaseModel):
    token: Optional[str] = None
